# Generated by Django 5.1.11 on 2025-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanWord',
            fields=[
                ('word', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AlterModelOptions(
            name='saying',
            options={'ordering': ['valid']},
        ),
        migrations.AlterField(
            model_name='saying',
            name='content',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='saying',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
